"""大纲节点领域资源 repository 抽象。"""

from typing import Protocol
from uuid import UUID

from app.business.novel_generate.nodes.outline.domain.models import (
    ChapterSummary,
    Outline,
    Seed,
    Skeleton,
    SkeletonVolume,
)


class OutlineRepository(Protocol):
    def save_seed(self, seed: Seed) -> Seed: ...

    def get_seed(self, seed_id: UUID) -> Seed | None: ...

    def save_skeleton(self, skeleton: Skeleton) -> Skeleton: ...

    def get_skeleton(self, skeleton_id: UUID) -> Skeleton | None: ...

    def get_skeleton_by_seed(self, seed_id: UUID) -> Skeleton | None: ...

    def get_volume(self, volume_id: UUID) -> SkeletonVolume | None: ...

    def get_chapter_summary(self, chapter_id: UUID) -> ChapterSummary | None: ...

    def save_chapter_summaries(
        self, summaries: list[ChapterSummary]
    ) -> list[ChapterSummary]: ...

    def get_chapters_by_volume(self, volume_id: UUID) -> list[ChapterSummary]: ...

    def delete_chapters_by_volume(self, volume_id: UUID) -> None: ...

    def mark_chapters_stale(self, volume_id: UUID) -> None: ...

    def update_skeleton_volume(self, volume: SkeletonVolume) -> SkeletonVolume: ...

    def update_chapter_summary(self, chapter: ChapterSummary) -> ChapterSummary: ...

    def save_outline(self, outline: Outline) -> Outline: ...

    def get_outline_by_seed(self, seed_id: UUID) -> Outline | None: ...
